name: GravityGuild
main: com.johncorby.gravityguild.Mainkt
version: 3.0
author: JohnCorby
description: Minigame for my server
depend: [FastAsyncWorldEdit, PlugMan]

permissions:
  gravityguild.admin:
    description: You can do everything.
    default: op
