name: GravityGuild
main: com.johncorby.gravityguild.Mainkt
version: 3.0-SNAPSHOT
author: JohnCorby
description: Minigame for my server
softdepend: [PlugMan]
api-version: 1.15

permissions:
  gravityguild.admin:
    description: You can do everything.
    default: op
