name: GravityGuild
main: com.johncorby.gravityguild.Mainkt
version: 3.0
author: JohnCorby
description: Minigame for my server
depend: [FastAsyncWorldEdit, PlugMan]

commands:
  gravityguild:
    description: Base GravityGuild command.
    aliases: gg

permissions:
  gravityguild.admin:
    description: You can do everything.
    default: op
